try {
    let a
    console.log(a.length)
} catch (error) {
    console.log("Hii")
}